name: nlp-research-template
channels:
  - conda-forge
  - https://ftp.osuosl.org/pub/open-ce/current/ # needed for binaries compiled for ppc64le
  - defaults # needed for some small packages (leveldb, ...)
dependencies:
  # - python=3.9 # or don't specify the version and use latest stable
  - pytorch=2.0.1 # OpenCE version 1.9
  # CUDA only for Linux (on compute server machine)
  - cudatoolkit=11.8 # OpenCE version 1.9
  - dargparser
  - wandb
  - lightning
  - transformers
  - tokenizers
  - datasets
  - loguru
  - tqdm

  # Dev dependencies
  - black
  - isort
  - flake8

  # Pip dependencies
  - pip
  - pip:
      - warmup-scheduler

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-ppc64le

