name: nlp-research-template
channels:
  - conda-forge
  - https://ftp.osuosl.org/pub/open-ce/current/ # needed for binaries compiled for ppc64le
  - defaults # needed for some small packages (leveldb, ...)
dependencies:
  - pytorch=1.13 # OpenCE version 1.8
  # CUDA only for Linux (on compute server machine)
  - cudatoolkit=11.4 # OpenCE version 1.8
  - click
  - dargparser
  - wandb
  - pytorch-lightning
  - transformers
  - tokenizers
  - datasets
  - loguru
  - black
  - isort
  - tqdm
  - pip:
      - warmup-scheduler

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-ppc64le

